[package]
name = "optcg"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
simplelog = "0.12.2"
